name: Deploy to SpaceWeb

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend  
      
      - name: Build frontend
        env:
          VITE_VK_CLIENT_ID: ${{ secrets.VITE_VK_CLIENT_ID }}
        run: npm run build
        working-directory: ./frontend
      
      - name: Deploy to SpaceWeb
        uses: appleboy/scp-action@v0.1.7
        with:
          host: fvh3.sweb.ru
          username: arsenijsto
          password: ${{ secrets.SPACEWEB_PASSWORD }}
          source: "./frontend/dist/*"
          target: "/home/a/arsenijsto/public_html/"
          strip_components: 2